
const languages = {
    en: {
        // Navigation
        navHome: "Home",
        navAbout: "About",
        navDonation: "Donation",
        navMembership: "Membership",
        navEvents: "Events",
        navContact: "Contact",

        // Hero Section
        heroTitle: "Building a Better Future, Together",
        heroSubtitle: "Join the Nav Yug Nirman Foundation in our mission to empower communities and create lasting change.",
        donateNow: "Donate Now",
        joinOurMission: "Join Our Mission",

        // About Page
        aboutTitle: "About Nav Yug Nirman Foundation",
        ourStory: "Our Story",
        storyContent: "Nav Yug Nirman Foundation was established with the vision of creating a society where every individual has the opportunity to live a dignified life. Our journey began with a small group of passionate individuals who wanted to make a difference in their communities. Today, we have grown into a thriving organization that has touched the lives of thousands.",
        ourMission: "Our Mission",
        missionContent: "Our mission is to empower underprivileged communities through sustainable initiatives in education, healthcare, and social welfare. We strive to create a world where everyone has access to basic necessities and the opportunity to reach their full potential.",
        ourLeadership: "Our Leadership",
        
        // Donation Page
        donationTitle: "Make a Donation",
        donationSubtitle: "Your donation will help us provide essential services to those in need. Every contribution, no matter how small, makes a difference.",
        selectAmount: "Select Amount",
        customAmount: "Or Enter Custom Amount",
        donorName: "Full Name",
        donorEmail: "Email Address",
        donorPhone: "Phone Number",
        
        // Membership Page
        membershipTitle: "Become a Member",
        membershipSubtitle: "Join us and be a part of the change.",
        memberName: "Full Name",
        memberEmail: "Email Address",
        memberPhone: "Phone Number",
        membershipType: "Membership Type",
        
        // Events Page
        eventsTitle: "Events",
        upcomingEvents: "Upcoming Events",
        pastEvents: "Past Events",
        
        // Contact Page
        contactTitle: "Contact Us",
        contactSubtitle: "Get in touch with us for any queries.",

        // Theme Toggle
        themeLight: "Light",
        themeDark: "Dark",

        // Document Generation
        receiptTitle: "Donation Receipt",
        receiptNo: "Receipt No.",
        date: "Date",
        donorDetails: "Donor Details",
        name: "Name",
        email: "Email",
        phone: "Phone",
        address: "Address",
        amount: "Amount",
        transactionRef: "Transaction Reference",
        bankDetails: "Bank Details",
        accountName: "Account Name",
        accountNumber: "Account Number",
        bankName: "Bank Name",
        upiDetails: "UPI Details",
        taxExemption: "Donations are exempt under Section 80G of the Income Tax Act, 1961.",
        thankYou: "Thank you for your generous contribution to Nav Yug Nirman Foundation.",
        downloadReceipt: "Download Receipt",

        certificateTitle: "Certificate of Membership",
        memberId: "Member ID",
        membershipCategory: "Membership Category",
        issueDate: "Issue Date",
        validUntil: "Valid Until",
        signature: "Signature",
        president: "President",
        secretary: "Secretary",
        downloadCertificate: "Download Certificate",

        idCardTitle: "Member ID Card",
        role: "Role",
        expiryDate: "Expiry Date",
        downloadIdCard: "Download ID Card",

        // Form fields (re-using existing keys where possible, adding new ones)
        fullName: "Full Name",
        emailAddress: "Email Address",
        phoneNumber: "Phone Number",
        selectAmount: "Select Amount",
        orEnterCustomAmount: "Or Enter Custom Amount",
        yourImpact: "Your Impact",
        bankDetailsSection: "Bank Details",
        upiQrCode: "UPI / QR Code",
        membershipType: "Membership Type",
        uploadPhoto: "Upload Photo",
        membershipBenefits: "Membership Benefits",
        generalMember: "General Member",
        lifeMember: "Life Member",
        patronMember: "Patron Member",
        certificatePreview: "Certificate Preview",
        registerForEvent: "Register for Event",
        eventName: "Event Name",
        participantName: "Participant Name",
        participantEmail: "Participant Email",
        messageSent: "Message Sent!",
        contactThankYou: "Thank you for contacting us. We will get back to you shortly.",
        pleaseCorrectErrors: "Please correct the errors in the form.",
        thankYouRegistering: "Thank you for registering! We will contact you shortly.",
        thankYouEventRegistering: "Thank you for registering for the event!",
        copiedToClipboard: "Copied to clipboard!",
        failedToCopy: "Failed to copy.",

        // Payment & Transaction
        transactionHistory: "Transaction History",
        transactionId: "Transaction ID",
        paymentId: "Payment ID",
        orderId: "Order ID",
        status: "Status",
        date: "Date",
        amount: "Amount",
        purpose: "Purpose",
        exportCsv: "Export to CSV",
        search: "Search",
        filterByStatus: "Filter by Status",
        all: "All",
        success: "Success",
        failed: "Failed",
        pending: "Pending",
        noTransactions: "No transactions found.",
        address: "Address",
        pan: "PAN (Optional)",
        donationPurpose: "Donation Purpose",
        anonymousDonation: "Donate Anonymously",
        paymentSuccessful: "Payment Successful!",
        paymentFailed: "Payment Failed!",
        paymentCancelled: "Payment Cancelled.",
        paymentProcessing: "Processing your payment...",
        paymentError: "An error occurred during payment.",
        generateReceipt: "Generate Receipt",
        generateCertificate: "Generate Certificate",
        generateIdCard: "Generate ID Card",

    },
    hi: {
        // Navigation
        navHome: "होम",
        navAbout: "हमारे बारे में",
        navDonation: "दान",
        navMembership: "सदस्यता",
        navEvents: "आयोजन",
        navContact: "संपर्क",

        // Hero Section
        heroTitle: "एक बेहतर भविष्य का निर्माण, एक साथ",
        heroSubtitle: "समुदायों को सशक्त बनाने और स्थायी परिवर्तन लाने के हमारे मिशन में नव युग निर्माण फाउंडेशन से जुड़ें।",
        donateNow: "अभी दान करें",
        joinOurMission: "हमारे मिशन में शामिल हों",

        // About Page
        aboutTitle: "नव युग निर्माण फाउंडेशन के बारे में",
        ourStory: "हमारी कहानी",
        storyContent: "नव युग निर्माण फाउंडेशन की स्थापना एक ऐसे समाज के निर्माण की दृष्टि से की गई थी जहाँ प्रत्येक व्यक्ति को सम्मानजनक जीवन जीने का अवसर मिले। हमारी यात्रा कुछ उत्साही व्यक्तियों के एक छोटे समूह के साथ शुरू हुई जो अपने समुदायों में बदलाव लाना चाहते थे। आज, हम एक संपन्न संगठन के रूप में विकसित हुए हैं जिसने हजारों लोगों के जीवन को छुआ है।",
        ourMission: "हमारा विशेष कार्य",
        missionContent: "हमारा मिशन शिक्षा, स्वास्थ्य सेवा और समाज कल्याण में स्थायी पहलों के माध्यम से वंचित समुदायों को सशक्त बनाना है। हम एक ऐसी दुनिया बनाने का प्रयास करते हैं जहाँ सभी को बुनियादी आवश्यकताएं उपलब्ध हों और अपनी पूरी क्षमता तक पहुँचने का अवसर मिले।",
        ourLeadership: "हमारा नेतृत्व",

        // Donation Page
        donationTitle: "दान करें",
        donationSubtitle: "आपका दान हमें जरूरतमंद लोगों को आवश्यक सेवाएं प्रदान करने में मदद करेगा। हर योगदान, चाहे कितना भी छोटा क्यों न हो, एक अंतर बनाता है।",
        selectAmount: "राशि चुनें",
        customAmount: "या कस्टम राशि दर्ज करें",
        donorName: "पूरा नाम",
        donorEmail: "ईमेल पता",
        donorPhone: "फ़ोन नंबर",

        // Membership Page
        membershipTitle: "सदस्य बनें",
        membershipSubtitle: "हमसे जुड़ें और बदलाव का हिस्सा बनें।",
        memberName: "पूरा नाम",
        memberEmail: "ईमेल पता",
        memberPhone: "फ़ोन नंबर",
        membershipType: "सदस्यता का प्रकार",

        // Events Page
        eventsTitle: "आयोजन",
        upcomingEvents: "आगामी आयोजन",
        pastEvents: "विगत आयोजन",

        // Contact Page
        contactTitle: "संपर्क करें",
        contactSubtitle: "किसी भी प्रश्न के लिए हमसे संपर्क करें।",

        // Theme Toggle
        themeLight: "लाइट",
        themeDark: "डार्क",

        // Document Generation
        receiptTitle: "दान रसीद",
        receiptNo: "रसीद संख्या",
        date: "दिनांक",
        donorDetails: "दाता का विवरण",
        name: "नाम",
        email: "ईमेल",
        phone: "फ़ोन",
        address: "पता",
        amount: "राशि",
        transactionRef: "लेनदेन संदर्भ",
        bankDetails: "बैंक विवरण",
        accountName: "खाता धारक का नाम",
        accountNumber: "खाता संख्या",
        bankName: "बैंक का नाम",
        upiDetails: "यूपीआई विवरण",
        taxExemption: "दान आयकर अधिनियम, 1961 की धारा 80G के तहत छूट प्राप्त हैं।",
        thankYou: "नव युग निर्माण फाउंडेशन में आपके उदार योगदान के लिए धन्यवाद।",
        downloadReceipt: "रसीद डाउनलोड करें",

        certificateTitle: "सदस्यता प्रमाण पत्र",
        memberId: "सदस्य आईडी",
        membershipCategory: "सदस्यता श्रेणी",
        issueDate: "जारी करने की तिथि",
        validUntil: "तक वैध",
        signature: "हस्ताक्षर",
        president: "अध्यक्ष",
        secretary: "सचिव",
        downloadCertificate: "प्रमाण पत्र डाउनलोड करें",

        idCardTitle: "सदस्य आईडी कार्ड",
        role: "भूमिका",
        expiryDate: "समाप्ति तिथि",
        downloadIdCard: "आईडी कार्ड डाउनलोड करें",

        // Form fields (re-using existing keys where possible, adding new ones)
        fullName: "पूरा नाम",
        emailAddress: "ईमेल पता",
        phoneNumber: "फ़ोन नंबर",
        selectAmount: "राशि चुनें",
        orEnterCustomAmount: "या कस्टम राशि दर्ज करें",
        yourImpact: "आपका प्रभाव",
        bankDetailsSection: "बैंक विवरण",
        upiQrCode: "यूपीआई / क्यूआर कोड",
        membershipType: "सदस्यता का प्रकार",
        uploadPhoto: "फोटो अपलोड करें",
        membershipBenefits: "सदस्यता लाभ",
        generalMember: "सामान्य सदस्य",
        lifeMember: "आजीवन सदस्य",
        patronMember: "संरक्षक सदस्य",
        certificatePreview: "प्रमाण पत्र पूर्वावलोकन",
        registerForEvent: "आयोजन के लिए पंजीकरण करें",
        eventName: "आयोजन का नाम",
        participantName: "प्रतिभागी का नाम",
        participantEmail: "प्रतिभागी का ईमेल",
        messageSent: "संदेश भेजा गया!",
        contactThankYou: "हमसे संपर्क करने के लिए धन्यवाद। हम आपसे शीघ्र ही संपर्क करेंगे।",
        pleaseCorrectErrors: "कृपया फ़ॉर्म में त्रुटियों को ठीक करें।",
        thankYouRegistering: "पंजीकरण के लिए धन्यवाद! हम आपसे शीघ्र ही संपर्क करेंगे।",
        thankYouEventRegistering: "आयोजन के लिए पंजीकरण करने के लिए धन्यवाद!",
        copiedToClipboard: "क्लिपबोर्ड पर कॉपी किया गया!",
        failedToCopy: "कॉपी करने में विफल।",
    }
};
